### ISSUE TITLE
No is_only_support_keycode_goto value.

### ISSUE THREAD

**Issue by Imikeeee** [ianchb/MIUI-AOD-Freely#4]
There is no is_only_support_keycode_goto value in monet.xml file. 

Phone:
Xiaomi Mi 10 Lite 5G , miui 13.0.4
![Screenshot_2023-03-25-20-03-21-039_com lonelycatgames Xplore](https://user-images.githubusercontent.com/38005932/227736510-5d75669e-1906-478a-ae17-01ffd1b18581.png)

**Comment by ianchb** [comment]
Please attach the full monet.xml file here.
Note: I'm very busy these days. I may not be able to solve your problem in time.

**Comment by ianchb** [comment]
Not receiving updates for a week.
Please open a new issue if you hope to solve the problem.
